ALTER TABLE "DateChangeRequest"
  ADD COLUMN IF NOT EXISTS "amountExpected" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "amountActual" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "paymentDoneDate" TEXT;
